// src/app/layout.js
import { Inter } from 'next/font/google'
import './globals.css'
import 'animate.css';
import { EmployeeProvider } from './dashboard/karyawan/context/EmployeeContext'; 
import { SidebarProvider } from './context/SidebarContext'; 


const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
      
        <SidebarProvider> {/* SidebarProvider */}
          <EmployeeProvider> {/* EmployeeProvider */}
            {children}
          </EmployeeProvider>
        </SidebarProvider>
        
      </body>
    </html>
  )
}
